### ISSUE TITLE
Report tx success or failure

### ISSUE THREAD

**Issue by Sirlupinwatson1** [invisible-college/democracy#48]
## Work-in-progress
This issue is not yet complete.

## Background
This task is part of a larger project to demonstrate zero-knowledge assets in a browser.
Zero-knowledge assets can benefit from a private messaging system, such as Whisper, for direct peer-to-peer, encrypted communication which is unreadable to another other party, including any intermediate servers hosting the static site, or the Whisper server itself.

### Description of the work order

- Find a way to instaure a box related to the Blockchain Network and transactions of the actual sender, when sending or receiving an amount of ERC20 token or cryptocurrency. 

- The Task is to display the status of transaction success or failure, as a box with nice looking design that will fit the existing mockup . It could be a redirect to Etherscan or the Blockchain Network web site related, but the box itself need to keep track of the transaction from the user is the main goal.

- The design should allow for multiple transactions to occur but also previous transaction statuses should scroll up, to show the history of all past transactions.

--------------------------------
### Description and Examples

A static demo, created with react-scripts, not connected to the blockchain, is currently running on:
https://vigilant-wiles-4b7d39.netlify.com/

## With source code in this directory:
https://github.com/invisible-college/democracy/tree/master/packages/zk-transfer-web

Your task is to take the first step in connecting this demo to the blockchain by adding an automatically created (Rinkeby) Ethereum address in place of the static fake address: 0x291F1ic810…2BgSdifB7
and make the text a link to the corresponding Etherscan page at https://rinkeby.etherscan.io

Here is a running example of a page that will auto-create an Ethereum account in the browser (running on a private testnet) using Democracy.js
https://demo-aztec.herokuapp.com/

This is the source code of the main HTML page:
https://github.com/invisible-college/democracy/blob/master/packages/aztec-web/public/index.html

You can adapt this code, with window.NODE_ENV='RINKEBY' in your own example.

### How to Work on This Task
Fork this repo and clone it locally onto your computer.

https://github.com/invisible-college/democracy#get-the-source-code-to-experiment-and-run-tests

Host your work-in-progress on Netlify and post that link in this thread as you work for feedback, help, and collaboration. For Netlify you may find the following helpful:

## Build commands

lerna bootstrap
cd packages/zk-transfer-web
react-scripts build
Build directory

packages/zk-transfer-web
Create a pull request against your forked repo (master branch) onto this repo (master branch), and commit and push your source code there as you work.

When it's ready, I'll merge from that PR onto the master branch and deploy your code to the Democracy.js Netlify instance. Please ask questions, and looking forward to working with you on this project.

![Gitcoinwork2](https://user-images.githubusercontent.com/55941045/74894672-ad226d80-535d-11ea-9401-d2eb079db035.png)

**Comment by cryptogoth** [comment]
This task is subsumed by #57
